/********************************************************************
* OGraphDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error OGraphDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableOGraphDict();
extern void G__cpp_setup_inheritanceOGraphDict();
extern void G__cpp_setup_typetableOGraphDict();
extern void G__cpp_setup_memvarOGraphDict();
extern void G__cpp_setup_globalOGraphDict();
extern void G__cpp_setup_memfuncOGraphDict();
extern void G__cpp_setup_funcOGraphDict();
extern void G__set_cpp_environmentOGraphDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/OGraph.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__OGraphDictLN_TClass;
extern G__linked_taginfo G__OGraphDictLN_TBuffer;
extern G__linked_taginfo G__OGraphDictLN_TMemberInspector;
extern G__linked_taginfo G__OGraphDictLN_TObject;
extern G__linked_taginfo G__OGraphDictLN_TNamed;
extern G__linked_taginfo G__OGraphDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__OGraphDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__OGraphDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__OGraphDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__OGraphDictLN_TAttLine;
extern G__linked_taginfo G__OGraphDictLN_TAttFill;
extern G__linked_taginfo G__OGraphDictLN_TAttMarker;
extern G__linked_taginfo G__OGraphDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__OGraphDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__OGraphDictLN_TGraph;
extern G__linked_taginfo G__OGraphDictLN_TGraphErrors;
extern G__linked_taginfo G__OGraphDictLN_OGraph;

/* STUB derived class for protected member access */
